### ISSUE TITLE
Scrolling past a carousel does not work in Safari when using a mouse

### ISSUE THREAD

**Issue by JayGeorge** [fancyapps/ui#529]
### Describe the bug

If you try to vertically scroll past a carousel in Safari, it will block any scroll interaction when the grabby-hand cursor is shown.

While this is probably acceptable with a very small carousel, most carousels tend to occupy a large vertical percentage of the screen, making this a big issue when trying to vertically scroll.

### Reproduction

- Make sure you're using a conventional mouse with a scroll wheel
- Go to the fancy apps Carousel demo page [here](https://fancyapps.com/carousel/) in Safari (currently I'm using 16.5.1)
- Hover over any carousel demo
- Try to scroll past it using a vertical scroll motion
- Observe that Safari will not let you do this

**Comment by rt-src** [comment]
I confirm this problem. Everything was fine in version 4.

**Comment by fancyapps** [comment]
Hi,

This should be fixed in the latest release.

**Comment by paradise-london** [comment]
Hi, I've just upgraded, but this still isn't working for me while using a mouse on 5.0.25 (trackpad is fine)

I'm loading in `https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.25/dist/carousel/carousel.umd.js`. Do I need to do anything else?

**Comment by JayGeorge** [comment]
Hi, I've just upgraded, but this still isn't working for me while using a mouse on 5.0.25 (trackpad is fine)

I'm loading in `https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0.25/dist/carousel/carousel.umd.js`. Do I need to do anything else?

**Comment by fancyapps** [comment]
If I remember correctly, it was simply caused by some CSS rule. I specifically bought a Macbook and a USB-C mouse to properly test and fix the issue, now it's working fine for me.

**Comment by JayGeorge** [comment]
Ouch, that's an expensive bug! I'd forgotten to update the CSS file. Fixed now, thanks :)
